name: Discord Notifier

on: [push] # This triggers the bot on every code push

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "**Update:** New code has been pushed to the repository by ${{ github.actor }}! \nCommit: ${{ github.event.head_commit.message }}"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
