name: Discord Notification
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook Update
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "Servo Skull of Progress Updates",
            "avatar_url": "https://cdn.discordapp.com/avatars/1555034390839562281/65ba2ff30cc1dcce15fab9c0c8df7840.webp?size=320",
            "content": "💀 **New code pushed to Product-Forge!** \nCommit: `${{ github.event.head_commit.message }}`"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
